spring:
  application:
    name: demo-consumer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/beast_tx?useUnicode=true&characterEncoding=utf-8&connectTimeout=6000&socketTimeout=6000&autoReconnect=true&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: 123456
server:
  port: 3111
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka/
#tx:
#  monitor:
#    ip: 127.0.0.1
#    port: 6789
